tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "bat"
brew "clang-format"
brew "fish"
brew "fzf"
brew "git-delta"
brew "helix"
brew "julia"
brew "neovim"
brew "ripgrep"
cask "blackhole-2ch"
cask "chromium"
cask "iterm2"
