" builtin plugins
runtime! ftplugin/man.vim

" appearance
color slate
set number

if !has("nvim")
  " both of these are true by default in neovim
  set showcmd
  set ttyfast
endif

set cursorline
au VimEnter * highlight clear CursorLine
au VimEnter * highlight CursorLineNr cterm=standout

let g:airline_theme = 'night_owl'
let g:airline_powerline_fonts = 1

" behavior
set clipboard^=unnamed,unnamedplus
set hidden
set scrolloff=10

" splits
set splitright
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" search
set ignorecase
set smartcase
set nohlsearch

" tabs
set expandtab
set tabstop=2
set shiftwidth=2
set shiftround

" netrw file explorer
let g:netrw_fastbrowse = 0
let g:netrw_banner=0
let g:netrw_liststyle=3

" operational files
if !has('nvim')
  if empty($XDG_CACHE_HOME)
    let $XDG_CACHE_HOME = '~/.cache'
  endif

  set undodir=$XDG_CACHE_HOME/vim,~/,/tmp
  set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
  set directory=$XDG_CACHE_HOME/vim,~/,/tmp
  set viminfo+=n$XDG_CACHE_HOME/vim/viminfo

  if empty($XDG_CONFIG_HOME)
    let $XDG_CONFIG_HOME = '~/.config'
  endif

  set runtimepath-=~/.vim
  set runtimepath^=$XDG_CONFIG_HOME/vim
  set runtimepath-=~/.vim/after
  set runtimepath+=$XDG_CONFIG_HOME/vim/after

  set packpath-=~/.vim
  set packpath^=$XDG_CONFIG_HOME/vim
  set packpath-=~/.vim/after
  set packpath+=$XDG_CONFIG_HOME/vim/after

  let $MYVIMRC = $XDG_CONFIG_HOME . "/vim/vimrc"
endif

" vcs gutter indicators
set signcolumn=yes
au VimEnter * highlight clear SignColumn
set updatetime=100

" masochism
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>
inoremap <Left> <nop>
inoremap <Right> <nop>

" html tag autoclose
let g:closetag_filetypes =
\ 'html,xhtml,phtml,javascript,javascriptreact,javascript.jsx,typescript,typescriptreact,typescript.tsx'
let g:closetag_xhtml_filetypes =
\ 'html,xhtml,phtml,javascript,javascriptreact,javascript.jsx,typescript,typescriptreact,typescript.tsx'
let g:closetag_emptyTags_caseSensitive = 1

" linting
let g:airline#extensions#ale#enabled = 1
let g:ale_fix_on_save = 1
set omnifunc=ale#completion#OmniFunc

nnoremap <C-M> :ALEFindReferences<CR>
nnoremap <C-N> :ALEGoToDefinition<CR>
nnoremap [r :ALEPreviousWrap<CR>
nnoremap ]r :ALENextWrap<CR>

" set ripgrep as grepprg
if executable("rg")
  set grepprg=rg\ --vimgrep\ --no-heading
  set grepformat=%f:%l:%c:%m,%f:%l:%m
endif

noremap gr :grep <cword><CR>
