[language-server.rust-analyzer]
check.command = "clippy"
check.extraArgs = ["--benches", "--examples", "--all-targets"]
hover.memoryLayout.niches = true

[[language]]
name = "rust"

[[language]]
name = "c"
auto-format = true

[[language]]
name = "cpp"
auto-format = true
